// Generated by gencpp from file marker_navigator/SetAttitude.msg
// DO NOT EDIT!


#ifndef MARKER_NAVIGATOR_MESSAGE_SETATTITUDE_H
#define MARKER_NAVIGATOR_MESSAGE_SETATTITUDE_H

#include <ros/service_traits.h>


#include <marker_navigator/SetAttitudeRequest.h>
#include <marker_navigator/SetAttitudeResponse.h>


namespace marker_navigator
{

struct SetAttitude
{

typedef SetAttitudeRequest Request;
typedef SetAttitudeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAttitude
} // namespace marker_navigator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::marker_navigator::SetAttitude > {
  static const char* value()
  {
    return "ea5e90e4318475285b6e38c8c4e25a8f";
  }

  static const char* value(const ::marker_navigator::SetAttitude&) { return value(); }
};

template<>
struct DataType< ::marker_navigator::SetAttitude > {
  static const char* value()
  {
    return "marker_navigator/SetAttitude";
  }

  static const char* value(const ::marker_navigator::SetAttitude&) { return value(); }
};


// service_traits::MD5Sum< ::marker_navigator::SetAttitudeRequest> should match
// service_traits::MD5Sum< ::marker_navigator::SetAttitude >
template<>
struct MD5Sum< ::marker_navigator::SetAttitudeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::marker_navigator::SetAttitude >::value();
  }
  static const char* value(const ::marker_navigator::SetAttitudeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::marker_navigator::SetAttitudeRequest> should match
// service_traits::DataType< ::marker_navigator::SetAttitude >
template<>
struct DataType< ::marker_navigator::SetAttitudeRequest>
{
  static const char* value()
  {
    return DataType< ::marker_navigator::SetAttitude >::value();
  }
  static const char* value(const ::marker_navigator::SetAttitudeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::marker_navigator::SetAttitudeResponse> should match
// service_traits::MD5Sum< ::marker_navigator::SetAttitude >
template<>
struct MD5Sum< ::marker_navigator::SetAttitudeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::marker_navigator::SetAttitude >::value();
  }
  static const char* value(const ::marker_navigator::SetAttitudeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::marker_navigator::SetAttitudeResponse> should match
// service_traits::DataType< ::marker_navigator::SetAttitude >
template<>
struct DataType< ::marker_navigator::SetAttitudeResponse>
{
  static const char* value()
  {
    return DataType< ::marker_navigator::SetAttitude >::value();
  }
  static const char* value(const ::marker_navigator::SetAttitudeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARKER_NAVIGATOR_MESSAGE_SETATTITUDE_H
