// Generated by gencpp from file marker_navigator/SetAttitudeYawRateRequest.msg
// DO NOT EDIT!


#ifndef MARKER_NAVIGATOR_MESSAGE_SETATTITUDEYAWRATEREQUEST_H
#define MARKER_NAVIGATOR_MESSAGE_SETATTITUDEYAWRATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marker_navigator
{
template <class ContainerAllocator>
struct SetAttitudeYawRateRequest_
{
  typedef SetAttitudeYawRateRequest_<ContainerAllocator> Type;

  SetAttitudeYawRateRequest_()
    : roll(0.0)
    , pitch(0.0)
    , yaw_rate(0.0)
    , thrust(0.0)  {
    }
  SetAttitudeYawRateRequest_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw_rate(0.0)
    , thrust(0.0)  {
  (void)_alloc;
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef float _thrust_type;
  _thrust_type thrust;





  typedef boost::shared_ptr< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetAttitudeYawRateRequest_

typedef ::marker_navigator::SetAttitudeYawRateRequest_<std::allocator<void> > SetAttitudeYawRateRequest;

typedef boost::shared_ptr< ::marker_navigator::SetAttitudeYawRateRequest > SetAttitudeYawRateRequestPtr;
typedef boost::shared_ptr< ::marker_navigator::SetAttitudeYawRateRequest const> SetAttitudeYawRateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator1> & lhs, const ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw_rate == rhs.yaw_rate &&
    lhs.thrust == rhs.thrust;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator1> & lhs, const ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marker_navigator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbcb966b3883bb0ba64d0ca912a2cc49";
  }

  static const char* value(const ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdbcb966b3883bb0bULL;
  static const uint64_t static_value2 = 0xa64d0ca912a2cc49ULL;
};

template<class ContainerAllocator>
struct DataType< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marker_navigator/SetAttitudeYawRateRequest";
  }

  static const char* value(const ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 roll\n"
"float32 pitch\n"
"float32 yaw_rate\n"
"float32 thrust\n"
;
  }

  static const char* value(const ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw_rate);
      stream.next(m.thrust);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetAttitudeYawRateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marker_navigator::SetAttitudeYawRateRequest_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "thrust: ";
    Printer<float>::stream(s, indent + "  ", v.thrust);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARKER_NAVIGATOR_MESSAGE_SETATTITUDEYAWRATEREQUEST_H
