// Generated by gencpp from file marker_navigator/SetAttitudeYawRate.msg
// DO NOT EDIT!


#ifndef MARKER_NAVIGATOR_MESSAGE_SETATTITUDEYAWRATE_H
#define MARKER_NAVIGATOR_MESSAGE_SETATTITUDEYAWRATE_H

#include <ros/service_traits.h>


#include <marker_navigator/SetAttitudeYawRateRequest.h>
#include <marker_navigator/SetAttitudeYawRateResponse.h>


namespace marker_navigator
{

struct SetAttitudeYawRate
{

typedef SetAttitudeYawRateRequest Request;
typedef SetAttitudeYawRateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAttitudeYawRate
} // namespace marker_navigator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::marker_navigator::SetAttitudeYawRate > {
  static const char* value()
  {
    return "a7d4321b4c1a6039ca301d0bd0fb422f";
  }

  static const char* value(const ::marker_navigator::SetAttitudeYawRate&) { return value(); }
};

template<>
struct DataType< ::marker_navigator::SetAttitudeYawRate > {
  static const char* value()
  {
    return "marker_navigator/SetAttitudeYawRate";
  }

  static const char* value(const ::marker_navigator::SetAttitudeYawRate&) { return value(); }
};


// service_traits::MD5Sum< ::marker_navigator::SetAttitudeYawRateRequest> should match
// service_traits::MD5Sum< ::marker_navigator::SetAttitudeYawRate >
template<>
struct MD5Sum< ::marker_navigator::SetAttitudeYawRateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::marker_navigator::SetAttitudeYawRate >::value();
  }
  static const char* value(const ::marker_navigator::SetAttitudeYawRateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::marker_navigator::SetAttitudeYawRateRequest> should match
// service_traits::DataType< ::marker_navigator::SetAttitudeYawRate >
template<>
struct DataType< ::marker_navigator::SetAttitudeYawRateRequest>
{
  static const char* value()
  {
    return DataType< ::marker_navigator::SetAttitudeYawRate >::value();
  }
  static const char* value(const ::marker_navigator::SetAttitudeYawRateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::marker_navigator::SetAttitudeYawRateResponse> should match
// service_traits::MD5Sum< ::marker_navigator::SetAttitudeYawRate >
template<>
struct MD5Sum< ::marker_navigator::SetAttitudeYawRateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::marker_navigator::SetAttitudeYawRate >::value();
  }
  static const char* value(const ::marker_navigator::SetAttitudeYawRateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::marker_navigator::SetAttitudeYawRateResponse> should match
// service_traits::DataType< ::marker_navigator::SetAttitudeYawRate >
template<>
struct DataType< ::marker_navigator::SetAttitudeYawRateResponse>
{
  static const char* value()
  {
    return DataType< ::marker_navigator::SetAttitudeYawRate >::value();
  }
  static const char* value(const ::marker_navigator::SetAttitudeYawRateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARKER_NAVIGATOR_MESSAGE_SETATTITUDEYAWRATE_H
