// Generated by gencpp from file marker_navigator/SetRatesYaw.msg
// DO NOT EDIT!


#ifndef MARKER_NAVIGATOR_MESSAGE_SETRATESYAW_H
#define MARKER_NAVIGATOR_MESSAGE_SETRATESYAW_H

#include <ros/service_traits.h>


#include <marker_navigator/SetRatesYawRequest.h>
#include <marker_navigator/SetRatesYawResponse.h>


namespace marker_navigator
{

struct SetRatesYaw
{

typedef SetRatesYawRequest Request;
typedef SetRatesYawResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRatesYaw
} // namespace marker_navigator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::marker_navigator::SetRatesYaw > {
  static const char* value()
  {
    return "8e9ec92299c2414ab4a1798226c4bd30";
  }

  static const char* value(const ::marker_navigator::SetRatesYaw&) { return value(); }
};

template<>
struct DataType< ::marker_navigator::SetRatesYaw > {
  static const char* value()
  {
    return "marker_navigator/SetRatesYaw";
  }

  static const char* value(const ::marker_navigator::SetRatesYaw&) { return value(); }
};


// service_traits::MD5Sum< ::marker_navigator::SetRatesYawRequest> should match
// service_traits::MD5Sum< ::marker_navigator::SetRatesYaw >
template<>
struct MD5Sum< ::marker_navigator::SetRatesYawRequest>
{
  static const char* value()
  {
    return MD5Sum< ::marker_navigator::SetRatesYaw >::value();
  }
  static const char* value(const ::marker_navigator::SetRatesYawRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::marker_navigator::SetRatesYawRequest> should match
// service_traits::DataType< ::marker_navigator::SetRatesYaw >
template<>
struct DataType< ::marker_navigator::SetRatesYawRequest>
{
  static const char* value()
  {
    return DataType< ::marker_navigator::SetRatesYaw >::value();
  }
  static const char* value(const ::marker_navigator::SetRatesYawRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::marker_navigator::SetRatesYawResponse> should match
// service_traits::MD5Sum< ::marker_navigator::SetRatesYaw >
template<>
struct MD5Sum< ::marker_navigator::SetRatesYawResponse>
{
  static const char* value()
  {
    return MD5Sum< ::marker_navigator::SetRatesYaw >::value();
  }
  static const char* value(const ::marker_navigator::SetRatesYawResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::marker_navigator::SetRatesYawResponse> should match
// service_traits::DataType< ::marker_navigator::SetRatesYaw >
template<>
struct DataType< ::marker_navigator::SetRatesYawResponse>
{
  static const char* value()
  {
    return DataType< ::marker_navigator::SetRatesYaw >::value();
  }
  static const char* value(const ::marker_navigator::SetRatesYawResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARKER_NAVIGATOR_MESSAGE_SETRATESYAW_H
