// Generated by gencpp from file marker_navigator/SetRatesYawRequest.msg
// DO NOT EDIT!


#ifndef MARKER_NAVIGATOR_MESSAGE_SETRATESYAWREQUEST_H
#define MARKER_NAVIGATOR_MESSAGE_SETRATESYAWREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marker_navigator
{
template <class ContainerAllocator>
struct SetRatesYawRequest_
{
  typedef SetRatesYawRequest_<ContainerAllocator> Type;

  SetRatesYawRequest_()
    : pitch_rate(0.0)
    , roll_rate(0.0)
    , yaw(0.0)
    , thrust(0.0)
    , frame_id()
    , update_frame(false)  {
    }
  SetRatesYawRequest_(const ContainerAllocator& _alloc)
    : pitch_rate(0.0)
    , roll_rate(0.0)
    , yaw(0.0)
    , thrust(0.0)
    , frame_id(_alloc)
    , update_frame(false)  {
  (void)_alloc;
    }



   typedef float _pitch_rate_type;
  _pitch_rate_type pitch_rate;

   typedef float _roll_rate_type;
  _roll_rate_type roll_rate;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _thrust_type;
  _thrust_type thrust;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;

   typedef uint8_t _update_frame_type;
  _update_frame_type update_frame;





  typedef boost::shared_ptr< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRatesYawRequest_

typedef ::marker_navigator::SetRatesYawRequest_<std::allocator<void> > SetRatesYawRequest;

typedef boost::shared_ptr< ::marker_navigator::SetRatesYawRequest > SetRatesYawRequestPtr;
typedef boost::shared_ptr< ::marker_navigator::SetRatesYawRequest const> SetRatesYawRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marker_navigator::SetRatesYawRequest_<ContainerAllocator1> & lhs, const ::marker_navigator::SetRatesYawRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pitch_rate == rhs.pitch_rate &&
    lhs.roll_rate == rhs.roll_rate &&
    lhs.yaw == rhs.yaw &&
    lhs.thrust == rhs.thrust &&
    lhs.frame_id == rhs.frame_id &&
    lhs.update_frame == rhs.update_frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marker_navigator::SetRatesYawRequest_<ContainerAllocator1> & lhs, const ::marker_navigator::SetRatesYawRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marker_navigator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "233064e7e905a6cfcb862fd91214ac8c";
  }

  static const char* value(const ::marker_navigator::SetRatesYawRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x233064e7e905a6cfULL;
  static const uint64_t static_value2 = 0xcb862fd91214ac8cULL;
};

template<class ContainerAllocator>
struct DataType< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marker_navigator/SetRatesYawRequest";
  }

  static const char* value(const ::marker_navigator::SetRatesYawRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pitch_rate\n"
"float32 roll_rate\n"
"float32 yaw\n"
"float32 thrust\n"
"string frame_id\n"
"bool update_frame\n"
;
  }

  static const char* value(const ::marker_navigator::SetRatesYawRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pitch_rate);
      stream.next(m.roll_rate);
      stream.next(m.yaw);
      stream.next(m.thrust);
      stream.next(m.frame_id);
      stream.next(m.update_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRatesYawRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marker_navigator::SetRatesYawRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marker_navigator::SetRatesYawRequest_<ContainerAllocator>& v)
  {
    s << indent << "pitch_rate: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_rate);
    s << indent << "roll_rate: ";
    Printer<float>::stream(s, indent + "  ", v.roll_rate);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "thrust: ";
    Printer<float>::stream(s, indent + "  ", v.thrust);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
    s << indent << "update_frame: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.update_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARKER_NAVIGATOR_MESSAGE_SETRATESYAWREQUEST_H
