// Generated by gencpp from file marker_navigator/SetRates.msg
// DO NOT EDIT!


#ifndef MARKER_NAVIGATOR_MESSAGE_SETRATES_H
#define MARKER_NAVIGATOR_MESSAGE_SETRATES_H

#include <ros/service_traits.h>


#include <marker_navigator/SetRatesRequest.h>
#include <marker_navigator/SetRatesResponse.h>


namespace marker_navigator
{

struct SetRates
{

typedef SetRatesRequest Request;
typedef SetRatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRates
} // namespace marker_navigator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::marker_navigator::SetRates > {
  static const char* value()
  {
    return "a7c908a2d3c593969f07004c267ff517";
  }

  static const char* value(const ::marker_navigator::SetRates&) { return value(); }
};

template<>
struct DataType< ::marker_navigator::SetRates > {
  static const char* value()
  {
    return "marker_navigator/SetRates";
  }

  static const char* value(const ::marker_navigator::SetRates&) { return value(); }
};


// service_traits::MD5Sum< ::marker_navigator::SetRatesRequest> should match
// service_traits::MD5Sum< ::marker_navigator::SetRates >
template<>
struct MD5Sum< ::marker_navigator::SetRatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::marker_navigator::SetRates >::value();
  }
  static const char* value(const ::marker_navigator::SetRatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::marker_navigator::SetRatesRequest> should match
// service_traits::DataType< ::marker_navigator::SetRates >
template<>
struct DataType< ::marker_navigator::SetRatesRequest>
{
  static const char* value()
  {
    return DataType< ::marker_navigator::SetRates >::value();
  }
  static const char* value(const ::marker_navigator::SetRatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::marker_navigator::SetRatesResponse> should match
// service_traits::MD5Sum< ::marker_navigator::SetRates >
template<>
struct MD5Sum< ::marker_navigator::SetRatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::marker_navigator::SetRates >::value();
  }
  static const char* value(const ::marker_navigator::SetRatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::marker_navigator::SetRatesResponse> should match
// service_traits::DataType< ::marker_navigator::SetRates >
template<>
struct DataType< ::marker_navigator::SetRatesResponse>
{
  static const char* value()
  {
    return DataType< ::marker_navigator::SetRates >::value();
  }
  static const char* value(const ::marker_navigator::SetRatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARKER_NAVIGATOR_MESSAGE_SETRATES_H
