// Generated by gencpp from file marker_navigator/SetVelocityYawRateRequest.msg
// DO NOT EDIT!


#ifndef MARKER_NAVIGATOR_MESSAGE_SETVELOCITYYAWRATEREQUEST_H
#define MARKER_NAVIGATOR_MESSAGE_SETVELOCITYYAWRATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marker_navigator
{
template <class ContainerAllocator>
struct SetVelocityYawRateRequest_
{
  typedef SetVelocityYawRateRequest_<ContainerAllocator> Type;

  SetVelocityYawRateRequest_()
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , yaw_rate(0.0)
    , frame_id()
    , update_frame(false)  {
    }
  SetVelocityYawRateRequest_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , yaw_rate(0.0)
    , frame_id(_alloc)
    , update_frame(false)  {
  (void)_alloc;
    }



   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;

   typedef float _vz_type;
  _vz_type vz;

   typedef float _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;

   typedef uint8_t _update_frame_type;
  _update_frame_type update_frame;





  typedef boost::shared_ptr< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetVelocityYawRateRequest_

typedef ::marker_navigator::SetVelocityYawRateRequest_<std::allocator<void> > SetVelocityYawRateRequest;

typedef boost::shared_ptr< ::marker_navigator::SetVelocityYawRateRequest > SetVelocityYawRateRequestPtr;
typedef boost::shared_ptr< ::marker_navigator::SetVelocityYawRateRequest const> SetVelocityYawRateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator1> & lhs, const ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.vz == rhs.vz &&
    lhs.yaw_rate == rhs.yaw_rate &&
    lhs.frame_id == rhs.frame_id &&
    lhs.update_frame == rhs.update_frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator1> & lhs, const ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marker_navigator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20ac62817b516f577b823aa7f141bed3";
  }

  static const char* value(const ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20ac62817b516f57ULL;
  static const uint64_t static_value2 = 0x7b823aa7f141bed3ULL;
};

template<class ContainerAllocator>
struct DataType< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marker_navigator/SetVelocityYawRateRequest";
  }

  static const char* value(const ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vx\n"
"float32 vy\n"
"float32 vz\n"
"float32 yaw_rate\n"
"string frame_id\n"
"bool update_frame\n"
;
  }

  static const char* value(const ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
      stream.next(m.yaw_rate);
      stream.next(m.frame_id);
      stream.next(m.update_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVelocityYawRateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marker_navigator::SetVelocityYawRateRequest_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<float>::stream(s, indent + "  ", v.vz);
    s << indent << "yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
    s << indent << "update_frame: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.update_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARKER_NAVIGATOR_MESSAGE_SETVELOCITYYAWRATEREQUEST_H
