// Generated by gencpp from file marker_navigator/SetVelocityYawRate.msg
// DO NOT EDIT!


#ifndef MARKER_NAVIGATOR_MESSAGE_SETVELOCITYYAWRATE_H
#define MARKER_NAVIGATOR_MESSAGE_SETVELOCITYYAWRATE_H

#include <ros/service_traits.h>


#include <marker_navigator/SetVelocityYawRateRequest.h>
#include <marker_navigator/SetVelocityYawRateResponse.h>


namespace marker_navigator
{

struct SetVelocityYawRate
{

typedef SetVelocityYawRateRequest Request;
typedef SetVelocityYawRateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVelocityYawRate
} // namespace marker_navigator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::marker_navigator::SetVelocityYawRate > {
  static const char* value()
  {
    return "d3735930254b75ba322bcc1e0750d89d";
  }

  static const char* value(const ::marker_navigator::SetVelocityYawRate&) { return value(); }
};

template<>
struct DataType< ::marker_navigator::SetVelocityYawRate > {
  static const char* value()
  {
    return "marker_navigator/SetVelocityYawRate";
  }

  static const char* value(const ::marker_navigator::SetVelocityYawRate&) { return value(); }
};


// service_traits::MD5Sum< ::marker_navigator::SetVelocityYawRateRequest> should match
// service_traits::MD5Sum< ::marker_navigator::SetVelocityYawRate >
template<>
struct MD5Sum< ::marker_navigator::SetVelocityYawRateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::marker_navigator::SetVelocityYawRate >::value();
  }
  static const char* value(const ::marker_navigator::SetVelocityYawRateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::marker_navigator::SetVelocityYawRateRequest> should match
// service_traits::DataType< ::marker_navigator::SetVelocityYawRate >
template<>
struct DataType< ::marker_navigator::SetVelocityYawRateRequest>
{
  static const char* value()
  {
    return DataType< ::marker_navigator::SetVelocityYawRate >::value();
  }
  static const char* value(const ::marker_navigator::SetVelocityYawRateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::marker_navigator::SetVelocityYawRateResponse> should match
// service_traits::MD5Sum< ::marker_navigator::SetVelocityYawRate >
template<>
struct MD5Sum< ::marker_navigator::SetVelocityYawRateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::marker_navigator::SetVelocityYawRate >::value();
  }
  static const char* value(const ::marker_navigator::SetVelocityYawRateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::marker_navigator::SetVelocityYawRateResponse> should match
// service_traits::DataType< ::marker_navigator::SetVelocityYawRate >
template<>
struct DataType< ::marker_navigator::SetVelocityYawRateResponse>
{
  static const char* value()
  {
    return DataType< ::marker_navigator::SetVelocityYawRate >::value();
  }
  static const char* value(const ::marker_navigator::SetVelocityYawRateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARKER_NAVIGATOR_MESSAGE_SETVELOCITYYAWRATE_H
