// Generated by gencpp from file interiit21/SetAttitude.msg
// DO NOT EDIT!


#ifndef INTERIIT21_MESSAGE_SETATTITUDE_H
#define INTERIIT21_MESSAGE_SETATTITUDE_H

#include <ros/service_traits.h>


#include <interiit21/SetAttitudeRequest.h>
#include <interiit21/SetAttitudeResponse.h>


namespace interiit21
{

struct SetAttitude
{

typedef SetAttitudeRequest Request;
typedef SetAttitudeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAttitude
} // namespace interiit21


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interiit21::SetAttitude > {
  static const char* value()
  {
    return "ea5e90e4318475285b6e38c8c4e25a8f";
  }

  static const char* value(const ::interiit21::SetAttitude&) { return value(); }
};

template<>
struct DataType< ::interiit21::SetAttitude > {
  static const char* value()
  {
    return "interiit21/SetAttitude";
  }

  static const char* value(const ::interiit21::SetAttitude&) { return value(); }
};


// service_traits::MD5Sum< ::interiit21::SetAttitudeRequest> should match
// service_traits::MD5Sum< ::interiit21::SetAttitude >
template<>
struct MD5Sum< ::interiit21::SetAttitudeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetAttitude >::value();
  }
  static const char* value(const ::interiit21::SetAttitudeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetAttitudeRequest> should match
// service_traits::DataType< ::interiit21::SetAttitude >
template<>
struct DataType< ::interiit21::SetAttitudeRequest>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetAttitude >::value();
  }
  static const char* value(const ::interiit21::SetAttitudeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interiit21::SetAttitudeResponse> should match
// service_traits::MD5Sum< ::interiit21::SetAttitude >
template<>
struct MD5Sum< ::interiit21::SetAttitudeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetAttitude >::value();
  }
  static const char* value(const ::interiit21::SetAttitudeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetAttitudeResponse> should match
// service_traits::DataType< ::interiit21::SetAttitude >
template<>
struct DataType< ::interiit21::SetAttitudeResponse>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetAttitude >::value();
  }
  static const char* value(const ::interiit21::SetAttitudeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERIIT21_MESSAGE_SETATTITUDE_H
