// Generated by gencpp from file interiit21/SetAttitudeYawRate.msg
// DO NOT EDIT!


#ifndef INTERIIT21_MESSAGE_SETATTITUDEYAWRATE_H
#define INTERIIT21_MESSAGE_SETATTITUDEYAWRATE_H

#include <ros/service_traits.h>


#include <interiit21/SetAttitudeYawRateRequest.h>
#include <interiit21/SetAttitudeYawRateResponse.h>


namespace interiit21
{

struct SetAttitudeYawRate
{

typedef SetAttitudeYawRateRequest Request;
typedef SetAttitudeYawRateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAttitudeYawRate
} // namespace interiit21


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interiit21::SetAttitudeYawRate > {
  static const char* value()
  {
    return "a7d4321b4c1a6039ca301d0bd0fb422f";
  }

  static const char* value(const ::interiit21::SetAttitudeYawRate&) { return value(); }
};

template<>
struct DataType< ::interiit21::SetAttitudeYawRate > {
  static const char* value()
  {
    return "interiit21/SetAttitudeYawRate";
  }

  static const char* value(const ::interiit21::SetAttitudeYawRate&) { return value(); }
};


// service_traits::MD5Sum< ::interiit21::SetAttitudeYawRateRequest> should match
// service_traits::MD5Sum< ::interiit21::SetAttitudeYawRate >
template<>
struct MD5Sum< ::interiit21::SetAttitudeYawRateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetAttitudeYawRate >::value();
  }
  static const char* value(const ::interiit21::SetAttitudeYawRateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetAttitudeYawRateRequest> should match
// service_traits::DataType< ::interiit21::SetAttitudeYawRate >
template<>
struct DataType< ::interiit21::SetAttitudeYawRateRequest>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetAttitudeYawRate >::value();
  }
  static const char* value(const ::interiit21::SetAttitudeYawRateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interiit21::SetAttitudeYawRateResponse> should match
// service_traits::MD5Sum< ::interiit21::SetAttitudeYawRate >
template<>
struct MD5Sum< ::interiit21::SetAttitudeYawRateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetAttitudeYawRate >::value();
  }
  static const char* value(const ::interiit21::SetAttitudeYawRateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetAttitudeYawRateResponse> should match
// service_traits::DataType< ::interiit21::SetAttitudeYawRate >
template<>
struct DataType< ::interiit21::SetAttitudeYawRateResponse>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetAttitudeYawRate >::value();
  }
  static const char* value(const ::interiit21::SetAttitudeYawRateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERIIT21_MESSAGE_SETATTITUDEYAWRATE_H
