// Generated by gencpp from file interiit21/SetPositionYawRate.msg
// DO NOT EDIT!


#ifndef INTERIIT21_MESSAGE_SETPOSITIONYAWRATE_H
#define INTERIIT21_MESSAGE_SETPOSITIONYAWRATE_H

#include <ros/service_traits.h>


#include <interiit21/SetPositionYawRateRequest.h>
#include <interiit21/SetPositionYawRateResponse.h>


namespace interiit21
{

struct SetPositionYawRate
{

typedef SetPositionYawRateRequest Request;
typedef SetPositionYawRateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPositionYawRate
} // namespace interiit21


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interiit21::SetPositionYawRate > {
  static const char* value()
  {
    return "63e77cdfe8f2694b3948c26357897f50";
  }

  static const char* value(const ::interiit21::SetPositionYawRate&) { return value(); }
};

template<>
struct DataType< ::interiit21::SetPositionYawRate > {
  static const char* value()
  {
    return "interiit21/SetPositionYawRate";
  }

  static const char* value(const ::interiit21::SetPositionYawRate&) { return value(); }
};


// service_traits::MD5Sum< ::interiit21::SetPositionYawRateRequest> should match
// service_traits::MD5Sum< ::interiit21::SetPositionYawRate >
template<>
struct MD5Sum< ::interiit21::SetPositionYawRateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetPositionYawRate >::value();
  }
  static const char* value(const ::interiit21::SetPositionYawRateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetPositionYawRateRequest> should match
// service_traits::DataType< ::interiit21::SetPositionYawRate >
template<>
struct DataType< ::interiit21::SetPositionYawRateRequest>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetPositionYawRate >::value();
  }
  static const char* value(const ::interiit21::SetPositionYawRateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interiit21::SetPositionYawRateResponse> should match
// service_traits::MD5Sum< ::interiit21::SetPositionYawRate >
template<>
struct MD5Sum< ::interiit21::SetPositionYawRateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetPositionYawRate >::value();
  }
  static const char* value(const ::interiit21::SetPositionYawRateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetPositionYawRateResponse> should match
// service_traits::DataType< ::interiit21::SetPositionYawRate >
template<>
struct DataType< ::interiit21::SetPositionYawRateResponse>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetPositionYawRate >::value();
  }
  static const char* value(const ::interiit21::SetPositionYawRateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERIIT21_MESSAGE_SETPOSITIONYAWRATE_H
