// Generated by gencpp from file interiit21/SetPosition.msg
// DO NOT EDIT!


#ifndef INTERIIT21_MESSAGE_SETPOSITION_H
#define INTERIIT21_MESSAGE_SETPOSITION_H

#include <ros/service_traits.h>


#include <interiit21/SetPositionRequest.h>
#include <interiit21/SetPositionResponse.h>


namespace interiit21
{

struct SetPosition
{

typedef SetPositionRequest Request;
typedef SetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPosition
} // namespace interiit21


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interiit21::SetPosition > {
  static const char* value()
  {
    return "2d7d37248af6d484bb92ea095ec530c1";
  }

  static const char* value(const ::interiit21::SetPosition&) { return value(); }
};

template<>
struct DataType< ::interiit21::SetPosition > {
  static const char* value()
  {
    return "interiit21/SetPosition";
  }

  static const char* value(const ::interiit21::SetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::interiit21::SetPositionRequest> should match
// service_traits::MD5Sum< ::interiit21::SetPosition >
template<>
struct MD5Sum< ::interiit21::SetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetPosition >::value();
  }
  static const char* value(const ::interiit21::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetPositionRequest> should match
// service_traits::DataType< ::interiit21::SetPosition >
template<>
struct DataType< ::interiit21::SetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetPosition >::value();
  }
  static const char* value(const ::interiit21::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interiit21::SetPositionResponse> should match
// service_traits::MD5Sum< ::interiit21::SetPosition >
template<>
struct MD5Sum< ::interiit21::SetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetPosition >::value();
  }
  static const char* value(const ::interiit21::SetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetPositionResponse> should match
// service_traits::DataType< ::interiit21::SetPosition >
template<>
struct DataType< ::interiit21::SetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetPosition >::value();
  }
  static const char* value(const ::interiit21::SetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERIIT21_MESSAGE_SETPOSITION_H
