// Generated by gencpp from file interiit21/SetRates.msg
// DO NOT EDIT!


#ifndef INTERIIT21_MESSAGE_SETRATES_H
#define INTERIIT21_MESSAGE_SETRATES_H

#include <ros/service_traits.h>


#include <interiit21/SetRatesRequest.h>
#include <interiit21/SetRatesResponse.h>


namespace interiit21
{

struct SetRates
{

typedef SetRatesRequest Request;
typedef SetRatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRates
} // namespace interiit21


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interiit21::SetRates > {
  static const char* value()
  {
    return "a7c908a2d3c593969f07004c267ff517";
  }

  static const char* value(const ::interiit21::SetRates&) { return value(); }
};

template<>
struct DataType< ::interiit21::SetRates > {
  static const char* value()
  {
    return "interiit21/SetRates";
  }

  static const char* value(const ::interiit21::SetRates&) { return value(); }
};


// service_traits::MD5Sum< ::interiit21::SetRatesRequest> should match
// service_traits::MD5Sum< ::interiit21::SetRates >
template<>
struct MD5Sum< ::interiit21::SetRatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetRates >::value();
  }
  static const char* value(const ::interiit21::SetRatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetRatesRequest> should match
// service_traits::DataType< ::interiit21::SetRates >
template<>
struct DataType< ::interiit21::SetRatesRequest>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetRates >::value();
  }
  static const char* value(const ::interiit21::SetRatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interiit21::SetRatesResponse> should match
// service_traits::MD5Sum< ::interiit21::SetRates >
template<>
struct MD5Sum< ::interiit21::SetRatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetRates >::value();
  }
  static const char* value(const ::interiit21::SetRatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetRatesResponse> should match
// service_traits::DataType< ::interiit21::SetRates >
template<>
struct DataType< ::interiit21::SetRatesResponse>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetRates >::value();
  }
  static const char* value(const ::interiit21::SetRatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERIIT21_MESSAGE_SETRATES_H
