// Generated by gencpp from file interiit21/SetVelocityRequest.msg
// DO NOT EDIT!


#ifndef INTERIIT21_MESSAGE_SETVELOCITYREQUEST_H
#define INTERIIT21_MESSAGE_SETVELOCITYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interiit21
{
template <class ContainerAllocator>
struct SetVelocityRequest_
{
  typedef SetVelocityRequest_<ContainerAllocator> Type;

  SetVelocityRequest_()
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , yaw(0.0)
    , frame_id()
    , update_frame(false)  {
    }
  SetVelocityRequest_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , yaw(0.0)
    , frame_id(_alloc)
    , update_frame(false)  {
  (void)_alloc;
    }



   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;

   typedef float _vz_type;
  _vz_type vz;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;

   typedef uint8_t _update_frame_type;
  _update_frame_type update_frame;





  typedef boost::shared_ptr< ::interiit21::SetVelocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interiit21::SetVelocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetVelocityRequest_

typedef ::interiit21::SetVelocityRequest_<std::allocator<void> > SetVelocityRequest;

typedef boost::shared_ptr< ::interiit21::SetVelocityRequest > SetVelocityRequestPtr;
typedef boost::shared_ptr< ::interiit21::SetVelocityRequest const> SetVelocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interiit21::SetVelocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interiit21::SetVelocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::interiit21::SetVelocityRequest_<ContainerAllocator1> & lhs, const ::interiit21::SetVelocityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.vz == rhs.vz &&
    lhs.yaw == rhs.yaw &&
    lhs.frame_id == rhs.frame_id &&
    lhs.update_frame == rhs.update_frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::interiit21::SetVelocityRequest_<ContainerAllocator1> & lhs, const ::interiit21::SetVelocityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace interiit21

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::interiit21::SetVelocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interiit21::SetVelocityRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interiit21::SetVelocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interiit21::SetVelocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interiit21::SetVelocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interiit21::SetVelocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interiit21::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32fb07e5a5c9a642047d9d8b3822c0f5";
  }

  static const char* value(const ::interiit21::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32fb07e5a5c9a642ULL;
  static const uint64_t static_value2 = 0x047d9d8b3822c0f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::interiit21::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interiit21/SetVelocityRequest";
  }

  static const char* value(const ::interiit21::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interiit21::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vx\n"
"float32 vy\n"
"float32 vz\n"
"float32 yaw\n"
"string frame_id\n"
"bool update_frame\n"
;
  }

  static const char* value(const ::interiit21::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interiit21::SetVelocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
      stream.next(m.yaw);
      stream.next(m.frame_id);
      stream.next(m.update_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVelocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interiit21::SetVelocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interiit21::SetVelocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<float>::stream(s, indent + "  ", v.vz);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
    s << indent << "update_frame: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.update_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERIIT21_MESSAGE_SETVELOCITYREQUEST_H
