// Generated by gencpp from file interiit21/SetVelocityYawRate.msg
// DO NOT EDIT!


#ifndef INTERIIT21_MESSAGE_SETVELOCITYYAWRATE_H
#define INTERIIT21_MESSAGE_SETVELOCITYYAWRATE_H

#include <ros/service_traits.h>


#include <interiit21/SetVelocityYawRateRequest.h>
#include <interiit21/SetVelocityYawRateResponse.h>


namespace interiit21
{

struct SetVelocityYawRate
{

typedef SetVelocityYawRateRequest Request;
typedef SetVelocityYawRateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVelocityYawRate
} // namespace interiit21


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interiit21::SetVelocityYawRate > {
  static const char* value()
  {
    return "d3735930254b75ba322bcc1e0750d89d";
  }

  static const char* value(const ::interiit21::SetVelocityYawRate&) { return value(); }
};

template<>
struct DataType< ::interiit21::SetVelocityYawRate > {
  static const char* value()
  {
    return "interiit21/SetVelocityYawRate";
  }

  static const char* value(const ::interiit21::SetVelocityYawRate&) { return value(); }
};


// service_traits::MD5Sum< ::interiit21::SetVelocityYawRateRequest> should match
// service_traits::MD5Sum< ::interiit21::SetVelocityYawRate >
template<>
struct MD5Sum< ::interiit21::SetVelocityYawRateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetVelocityYawRate >::value();
  }
  static const char* value(const ::interiit21::SetVelocityYawRateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetVelocityYawRateRequest> should match
// service_traits::DataType< ::interiit21::SetVelocityYawRate >
template<>
struct DataType< ::interiit21::SetVelocityYawRateRequest>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetVelocityYawRate >::value();
  }
  static const char* value(const ::interiit21::SetVelocityYawRateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interiit21::SetVelocityYawRateResponse> should match
// service_traits::MD5Sum< ::interiit21::SetVelocityYawRate >
template<>
struct MD5Sum< ::interiit21::SetVelocityYawRateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetVelocityYawRate >::value();
  }
  static const char* value(const ::interiit21::SetVelocityYawRateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetVelocityYawRateResponse> should match
// service_traits::DataType< ::interiit21::SetVelocityYawRate >
template<>
struct DataType< ::interiit21::SetVelocityYawRateResponse>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetVelocityYawRate >::value();
  }
  static const char* value(const ::interiit21::SetVelocityYawRateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERIIT21_MESSAGE_SETVELOCITYYAWRATE_H
