// Generated by gencpp from file interiit21/SetVelocity.msg
// DO NOT EDIT!


#ifndef INTERIIT21_MESSAGE_SETVELOCITY_H
#define INTERIIT21_MESSAGE_SETVELOCITY_H

#include <ros/service_traits.h>


#include <interiit21/SetVelocityRequest.h>
#include <interiit21/SetVelocityResponse.h>


namespace interiit21
{

struct SetVelocity
{

typedef SetVelocityRequest Request;
typedef SetVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVelocity
} // namespace interiit21


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interiit21::SetVelocity > {
  static const char* value()
  {
    return "ea087cf108d7c37634cddd53597622ce";
  }

  static const char* value(const ::interiit21::SetVelocity&) { return value(); }
};

template<>
struct DataType< ::interiit21::SetVelocity > {
  static const char* value()
  {
    return "interiit21/SetVelocity";
  }

  static const char* value(const ::interiit21::SetVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::interiit21::SetVelocityRequest> should match
// service_traits::MD5Sum< ::interiit21::SetVelocity >
template<>
struct MD5Sum< ::interiit21::SetVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetVelocity >::value();
  }
  static const char* value(const ::interiit21::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetVelocityRequest> should match
// service_traits::DataType< ::interiit21::SetVelocity >
template<>
struct DataType< ::interiit21::SetVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetVelocity >::value();
  }
  static const char* value(const ::interiit21::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interiit21::SetVelocityResponse> should match
// service_traits::MD5Sum< ::interiit21::SetVelocity >
template<>
struct MD5Sum< ::interiit21::SetVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interiit21::SetVelocity >::value();
  }
  static const char* value(const ::interiit21::SetVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interiit21::SetVelocityResponse> should match
// service_traits::DataType< ::interiit21::SetVelocity >
template<>
struct DataType< ::interiit21::SetVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::interiit21::SetVelocity >::value();
  }
  static const char* value(const ::interiit21::SetVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERIIT21_MESSAGE_SETVELOCITY_H
